// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using NIHR.UCLH.Research.Domain;


namespace NIHR.UCLH.Research.DAL.NIHR.UCLH.Research.DAL
{
    public partial class NIHRUCLHResearchDBContext : DbContext
    {
        public NIHRUCLHResearchDBContext()
        {
        }

        public NIHRUCLHResearchDBContext(DbContextOptions<NIHRUCLHResearchDBContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Admission> Admission { get; set; }
        public virtual DbSet<Patient> Patient { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Admission>(entity =>
            {
                entity.Property(e => e.AdmissionId).HasColumnName("Admission_Id");

                entity.Property(e => e.AdmissionSource)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName(" Admission_Source");

                entity.Property(e => e.DischargeTo)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName(" Discharge_To");

                entity.Property(e => e.PatientId).HasColumnName("Patient_Id");

                entity.Property(e => e.VisitEndDate)
                    .HasColumnType("datetime")
                    .HasColumnName(" Visit_End_Date");

                entity.Property(e => e.VisitEndDatetime)
                    .HasColumnType("datetime")
                    .HasColumnName("Visit_End_Datetime");

                entity.Property(e => e.VisitStartDate)
                    .HasColumnType("datetime")
                    .HasColumnName("Visit_Start_Date");

                entity.Property(e => e.VisitStartDatetime)
                    .HasColumnType("datetime")
                    .HasColumnName(" Visit_Start_Datetime");

                entity.HasOne(d => d.Patient)
                    .WithMany(p => p.Admission)
                    .HasForeignKey(d => d.PatientId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Admission_ToTable");
            });

            modelBuilder.Entity<Patient>(entity =>
            {
                entity.Property(e => e.PatientId).HasColumnName("Patient_Id");

                entity.Property(e => e.BirthDatetime)
                    .HasColumnType("datetime")
                    .HasColumnName("Birth_Datetime");

                entity.Property(e => e.DayOfBirth).HasColumnName("Day_Of_Birth");

                entity.Property(e => e.DeathDatetime)
                    .HasColumnType("datetime")
                    .HasColumnName("Death_Datetime");

                entity.Property(e => e.Ethnicity)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.FullName)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasColumnName("Full_Name");

                entity.Property(e => e.MonthOfBirth).HasColumnName("Month_Of_Birth");

                entity.Property(e => e.SexAtBirth)
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .HasColumnName("Sex_At_Birth");

                entity.Property(e => e.YearOfBirth).HasColumnName("Year_Of_Birth");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}