// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

using LINQtoCSV;
using System;
using System.Collections.Generic;

namespace NIHR.UCLH.Research.Domain
{
    public partial class Patient
    {
        public Patient()
        {
            Admission = new HashSet<Admission>();
        }
        [CsvColumn(Name = "patient_id")]
        public int PatientId { get; set; }
        [CsvColumn(Name = "full_name")]
        public string FullName { get; set; }
        [CsvColumn(Name = "sex_at_birth")]
        public string SexAtBirth { get; set; }
        [CsvColumn(Name = "ethnicity")]
        public string Ethnicity { get; set; }
        [CsvColumn(Name = "year_of_birth")]
        public int YearOfBirth { get; set; }
        [CsvColumn(Name = "month_of_birth")]
        public int MonthOfBirth { get; set; }
        [CsvColumn(Name = "day_of_birth")]
        public int DayOfBirth { get; set; }
        [CsvColumn(Name = "birth_datetime")]
        public DateTime BirthDatetime { get; set; }
        [CsvColumn(Name = "death_datetime")]
        public DateTime? DeathDatetime { get; set; }

        public virtual ICollection<Admission> Admission { get; set; }
    }
}